app: serverless-demo
service: serverless-demo-ui

nextjs-demo:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    runtime: nodejs12.x
    nextConfigDir: ./${env.REPO}
    domain:
      - ${env.DOMAIN}
    bucketName: ${env.BUCKET}
    priceClass: PriceClass_100
    build:
      env:
        NEXT_PUBLIC_API_BASE_URL: ${env.API_BASE_URL}
