name: API Deployment Workflow

on:
  repository_dispatch:
    types: [api-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      NPM_CONFIG_USERCONFIG: ~/.npmrc
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@saintybalboa'
      - name: Set NPM Auth Token
        run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc'
      - name: Install dependencies
        run: |
          npm i @saintybalboa/auth@0.0.4
      - name: Checkout the API repository
        uses: actions/checkout@v2
        with:
          path: api/${{ github.event.client_payload.repo }}
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.client_payload.commit-hash }}
      - name: Certificate check
        working-directory: ''
        run: |
          HOSTED_ZONE_ID=${{ secrets.HOSTED_ZONE_ID }} \
          DOMAIN=api-dev.msswebdevelopment.com \
          REPO=${{ github.event.client_payload.repo }} \
          make create-cert
      - name: Deploy
        working-directory: api
        run: |
          DOMAIN=api-dev.msswebdevelopment.com \
          REPO=${{ github.event.client_payload.repo }} \
          make deploy
