name: API Deployment Workflow

on:
  repository_dispatch:
    types: [api-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i -g serverless
          npm i
      - name: Checkout the API repository
        uses: actions/checkout@v2
        with:
          path: api/${{ github.event.client_payload.repo }}
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.client_payload.commit-hash }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Certificate check
        working-directory: ''
        run: |
          HOSTED_ZONE_ID=${{ secrets.HOSTED_ZONE_ID }} \
          DOMAIN=api-dev.msswebdevelopment.com \
          REPO=${{ github.event.client_payload.repo }} \
          make create-cert
      - name: Set NPM Auth Token
        working-directory: api/${{ github.event.client_payload.repo }}
        run: |
          echo "@saintybalboa:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
          ls node_modules/@saintybalboa
      - name: Deploy
        working-directory: api
        run: |
          DOMAIN=api-dev.msswebdevelopment.com \
          REPO=${{ github.event.client_payload.repo }} \
          make deploy
