name: NextJS Demo Manual Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: 'Enter the commit hash or branch'
        required: true
        default: 'main'
      domain-prefix:
        description: 'Enter the domain prefix'
        required: true
        default: 'www'
      domain:
        description: 'Enter the domain name'
        required: true
        default: 'msswebdevelopment.com'
      api-base-url:
        description: 'Enter the api base url'
        required: true
        default: 'https://api.msswebdevelopment.com'
      repo:
        description: 'Github repository that contains the API source code'
        required: true
        default: 'saintybalboa/nextjs-demo'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm i -g serverless
          npm i
      - name: Checkout the UI repository
        uses: actions/checkout@v2
        with:
          path: ui/${{ github.event.inputs.repo }}
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.inputs.commit-hash }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        working-directory: ui
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          DOMAIN_PREFIX=${{ github.event.inputs.domain-prefix }} \
          DOMAIN=${{ github.event.inputs.domain }} \
          API_BASE_URL=${{ github.event.inputs.api-base-url }} \
          BUCKET=serverless-demo-ui-bucket-${{ github.event.inputs.domain-prefix }} \
          REPO=${{ github.event.inputs.repo }} \
          make deploy
